/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package autocorrectpoo;

/**
 *
 * @author davidzarate
 */
public class PanelEscritura extends javax.swing.JPanel {

    /**
     * Creates new form PanelEscritura
     * @param autor
     * @param parentDialog
     */
    public PanelEscritura(Autor autor, javax.swing.JDialog parentDialog) {
        initComponents();
        this.autor = autor;
        this.parentDialog = parentDialog;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textAreaScrollPane = new javax.swing.JScrollPane();
        escrituraTextArea = new javax.swing.JTextArea();
        corregirButton = new javax.swing.JButton();
        guardarButton = new javax.swing.JButton();
        guardarEnDiccionarioButton = new javax.swing.JButton();

        escrituraTextArea.setColumns(20);
        escrituraTextArea.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        escrituraTextArea.setLineWrap(true);
        escrituraTextArea.setRows(5);
        escrituraTextArea.setWrapStyleWord(true);
        textAreaScrollPane.setViewportView(escrituraTextArea);

        corregirButton.setText("Corregir Ortografía");
        corregirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                corregirButtonActionPerformed(evt);
            }
        });

        guardarButton.setText("Guardar y Salir ");
        guardarButton.setPreferredSize(new java.awt.Dimension(163, 29));
        guardarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarButtonActionPerformed(evt);
            }
        });

        guardarEnDiccionarioButton.setText("Guardar en Diccionario");
        guardarEnDiccionarioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarEnDiccionarioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textAreaScrollPane)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(corregirButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(guardarEnDiccionarioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(6, 6, 6)
                        .addComponent(guardarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textAreaScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(corregirButton, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(guardarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(guardarEnDiccionarioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void corregirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_corregirButtonActionPerformed
        String texto = escrituraTextArea.getText();
        String textoChecado = Corrector.corregirTexto(texto);
        escrituraTextArea.setText(texto + "\n\n\n" + "Propuesta:\n" + textoChecado);
    }//GEN-LAST:event_corregirButtonActionPerformed

    private void guardarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarButtonActionPerformed
        parentDialog.dispose();
    }//GEN-LAST:event_guardarButtonActionPerformed

    private void guardarEnDiccionarioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarEnDiccionarioButtonActionPerformed
        String palabra = javax.swing.JOptionPane.showInputDialog("Agregar palabra");
        if(palabra!=null){
            Corrector.agregarPalabraADiccionario(palabra);
        }
    }//GEN-LAST:event_guardarEnDiccionarioButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton corregirButton;
    private javax.swing.JTextArea escrituraTextArea;
    private javax.swing.JButton guardarButton;
    private javax.swing.JButton guardarEnDiccionarioButton;
    private javax.swing.JScrollPane textAreaScrollPane;
    // End of variables declaration//GEN-END:variables

    private Autor autor;
    private javax.swing.JDialog parentDialog;
}
